### ISSUE TITLE
Unexpected token when importing css

### ISSUE THREAD

**Issue by tannerlinsley** [bclinkinbeard/partialify#17]
```javascript
var test = require("angular-grid/dist/angular-grid.css")
```
```
Github/myapp/node_modules/angular-grid/dist/angular-grid.css:1
ag-grid-a2 {
           ^
ParseError: Unexpected token
```

The file content doesn't contain anything crazy, just a vendor css file for angular-grid:

```css
ag-grid-a2 {
  display: inline-block;
}
.ag-root {
  font-size: 14px;
  cursor: default;
/* set to relative, so absolute popups appear relative to this */
  position: relative;
/* disable user mouse selection */
  -webkit-user-select: none;
  -moz-user-select: none;
  -ms-user-select: none;
  user-select: none;
  -webkit-box-sizing: border-box;
  -moz-box-sizing: border-box;
  box-sizing: border-box;
/* was getting some 'should be there' scrolls, this sorts it out */
  overflow: hidden;
}
.ag-no-scrolls {
  white-space: nowrap;
  display: inline-block;
}
.ag-scrolls {
  height: 100%;
}
.ag-popup-backdrop {
  position: fixed;
  left: 0px;
  top: 0px;
  width: 100%;
  height: 100%;
}
...
```
